# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0003_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_number',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
